name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  deploy-pages:
    name: Deploy Pages
    runs-on: ubuntu-24.04
    concurrency:
      group: pages
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm
        uses: threeal/setup-pnpm-action@v2.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm vite build

      - name: Deploy pages
        uses: cloudflare/wrangler-action@v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }}
